version: "3.8"
services:
  frontend:
    build:
      context: ./hello-frontend
    ports:
      - "3000:80"
    container_name: frontend-app

  backend:
    build:
      context: ./hello-backend
    ports:
      - "5000:5000"
    container_name: backend-app
